#!/usr/bin/bash
# Ubuntu 22.04

# usage-1: ngrok config add-authtoken <token>
# usage-2: ngrok http 3000 ! für Grafana 

curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
